# -*- mode: python; -*-
#
# This is the principle SConscript file, invoked by the SConstruct.  Its job is
# to delegate to any and all per-module SConscript files.

Import('env')
Import('module_sconscripts')

# NOTE: We must do third_party first as it adds methods to the environment
# that we need in the normous sconscript
env = env.Clone()
env.SConscript('third_party/SConscript', exports=['env'])

# Inject boost and pcre from third_party globally for all core normous code
# and modules. Ideally, pcre wouldn't be here, but enough things require it
# now that it seems hopeless to remove it now.
env = env.Clone()
env.InjectThirdPartyIncludePaths(libraries=[
    'boost',
    'pcre',
])

# Run the core normousdb SConscript.
env.SConscript('normous/SConscript', exports=['env'])

# Run SConscripts for any modules in play
env.SConscript(module_sconscripts, exports=['env'])
